// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrcnfbremravivufwewx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxyY25mYnJlbXJhdml2dWZ3ZXd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NjYyNTQsImV4cCI6MjA2NzI0MjI1NH0.RrGsSbJ9Nm60DkAEiUe_tbW06knwE83xzI3n3G8t-U0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});